---
root:
  _type: array
  _ignore_extra_keys: true
  _children:
    site:
      _type: array
      _ignore_extra_keys: true
      _children:
        title:
          _type: text
          _not_empty: true
        base_url:
          _type: pattern
          _required: true
          _pattern: /\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i
        index:
          _type: text
          _required: true
        post_url:
          _type: text
          _required: true
        target_dir:
          _type: text
        cache_dir:
          _type: text
        plugin_dir:
          _type: text

    template:
      _type: array
      _ignore_extra_keys: true
      _required: true
      _children:
        path:
          _type: text
        default_engine:
          _type: text
          _required: true

    posts:
      _type: array
      _ignore_extra_keys: true
      _children:
        path:
          _type: text
        new_post_pattern:
          _type: text

    collections:
      _type: array
      _ignore_extra_keys: true
      _children:
        path:
          _type: text
        per_page:
          _type: number
          _required: true
